    swagger: "2.0"
    info:
      title: gcpcmsauth
      description: "For authentication from OneCloud Portal team"
      version: "1.0.0"
    schemes:
      - "https"
    produces:
      - application/json
    securityDefinitions:
       api_key:
          type: "apiKey"
          name: "key"
          in: "query"
    paths:
      /cmsapp:
         post:
          description: "CMS for Policy binding based on defined roles"
          operationId: policybind
          x-google-backend:
            address: https://cms-oakbzd4pxq-uk.a.run.app
          security:
            - api_key : []
          
          responses:
            200:
              description: "Success."
              schema:
                type: string
            400:
              description: "Destination is Unavailable."